import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";

import "./globals.css";

export const metadata: Metadata = {
  title: "Stratwise",
  description: "Generated by Talha",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${GeistSans.variable} antialiased h-full`}>
        {children}
      </body>
    </html>
  );
}
